## FEATURES

Date: 2021-10-20

Grübchenabstand DL-DR [mm], Rumpflänge VP-DM [mm], Rumpfneigung VP-DM [°], Lotabweichung VP-DM [°], Seitabweichung VP-DM (RMS) [mm], Oberflächenrotation (RMS) [°], Kyphosewinkel VP-T12 [°] Lordosewinkel T12-DM [°], Beckenneigung (Symmetrielinie) [°], Beckentorsion DL-DR [°], Beckenhochstand [°], Beckenrotation [°] 

###### translation: 
Dimple distance DL-DR [mm], torso length VP-DM [mm], torso inclination VP-DM [°], vertical deviation VP-DM [°], lateral deviation VP-DM (RMS) [mm], surface rotation (RMS) [°] , Kyphosis angle VP-T12 [°] lordosis angle T12-DM [°], pelvic inclination (line of symmetry) [°], pelvic torsion DL-DR [°], elevated pelvis [°], pelvic rotation [°]

In [1]:
#Import necessary Libraries 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# ignore unnecessary warnings
import warnings
warnings.filterwarnings('ignore')

In [33]:
#load the k-pseudonymized.csv dataset
k_pseudonymized = pd.read_csv('../Trina Glory Project Work/Data sets/k-pseudonymized.csv',sep='\t')
k_pseudonymized = pd.DataFrame(data = k_pseudonymized[['Erstellt am','age','Weiblich/Männlich','Grübchenabstand DL-DR [mm]', 'Rumpflänge VP-DM [mm]', "Rumpfneigung VP-DM [°]", "Lotabweichung VP-DM [°]","Seitabweichung VP-DM (RMS) [mm]", "Oberflächenrotation (RMS) [°]", "Kyphosewinkel VP-T12 [°]", "Lordosewinkel T12-DM [°]","Beckenneigung (Symmetrielinie) [°]", "Beckentorsion DL-DR [°]", "Beckenhochstand [°]","Beckenrotation [°]"]])

In [34]:
# view the first 5 of our dataset
k_pseudonymized.head()

,Erstellt am,age,Weiblich/Männlich,Grübchenabstand DL-DR [mm],Rumpflänge VP-DM [mm],Rumpfneigung VP-DM [°],Lotabweichung VP-DM [°],Seitabweichung VP-DM (RMS) [mm],Oberflächenrotation (RMS) [°],Kyphosewinkel VP-T12 [°],Lordosewinkel T12-DM [°],Beckenneigung (Symmetrielinie) [°],Beckentorsion DL-DR [°],Beckenhochstand [°],Beckenrotation [°]
0,2013-01-07 11:58:35,"(60, 70]",F,"106,6",520,"13,3","-4,8","16,3","6,909289","43,9","37,3","39,6","2,2","3,7","-0,4"
1,2013-01-07 11:57:35,"(60, 70]",F,"106,3","506,9","10,5","-4,7","14,5","8,003676","36,8","40,6","39,9","1,8","1,6","-2,2"
2,2013-01-07 11:49:17,"(60, 70]",F,106,"513,7",10,"-4,5","13,7","4,481077",37,"39,4","39,8",2,"1,7","0,2"
3,2015-02-10 04:28:13,"(40, 50]",F,"102,1","445,9","5,3","-0,7","4,2","3,060272","38,1","36,9","34,5","-0,9","3,3","4,6"
4,2015-02-10 04:27:03,"(40, 50]",F,"102,1","448,6","4,8","-0,7","4,9","3,081126","38,4",37,"32,1","-0,8","3,3","2,3"

In [35]:
# info of k_pseudonymized dataset
k_pseudonymized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12828 entries, 0 to 12827
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Erstellt am                         12828 non-null  object
 1   age                                 12828 non-null  object
 2   Weiblich/Männlich                   12828 non-null  object
 3   Grübchenabstand DL-DR [mm]          12828 non-null  object
 4   Rumpflänge VP-DM [mm]               12828 non-null  object
 5   Rumpfneigung VP-DM [°]              12828 non-null  object
 6   Lotabweichung VP-DM [°]             12828 non-null  object
 7   Seitabweichung VP-DM (RMS) [mm]     12828 non-null  object
 8   Oberflächenrotation (RMS) [°]       12828 non-null  object
 9   Kyphosewinkel VP-T12 [°]            12826 non-null  object
 10  Lordosewinkel T12-DM [°]            12824 non-null  object
 11  Beckenneigung (Symmetrielinie) [°]  12828 non-null  object
 12  Beckentorsion DL-DR [°]             12828 non-null  object
 13  Beckenhochstand [°]                 12827 non-null  object
 14  Beckenrotation [°]                  12790 non-null  object
dtypes: object(15)
memory usage: 1.5+ MB

In [36]:
#NOTE:
# we have 14 columns + age and Erstellt am [Date] columns making 14 colums in total
# presently every colunm is reagarded as object
# we have 12,828 sampls available

In [37]:
# check if there are missing rows from the sample
k_pseudonymized.isna().sum()

Erstellt am                            0
age                                    0
Weiblich/Männlich                      0
Grübchenabstand DL-DR [mm]             0
Rumpflänge VP-DM [mm]                  0
Rumpfneigung VP-DM [°]                 0
Lotabweichung VP-DM [°]                0
Seitabweichung VP-DM (RMS) [mm]        0
Oberflächenrotation (RMS) [°]          0
Kyphosewinkel VP-T12 [°]               2
Lordosewinkel T12-DM [°]               4
Beckenneigung (Symmetrielinie) [°]     0
Beckentorsion DL-DR [°]                0
Beckenhochstand [°]                    1
Beckenrotation [°]                    38
dtype: int64

In [38]:
# colunm Kyphosewinkel VP-T12 [°] contains 2 missing values
# colunm Lordosewinkel T12-DM [°] contains 4 missing values
# colunm Beckenhochstand [°] contains 1 missing values
# colunm Beckenrotation [°] contains 38 missing values

In [39]:
# convert the Erstellt am [date] column to date time ⌚ 
k_pseudonymized['Erstellt am'] = pd.to_datetime(k_pseudonymized['Erstellt am'])
# check...
k_pseudonymized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12828 entries, 0 to 12827
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Erstellt am                         12828 non-null  datetime64[ns]
 1   age                                 12828 non-null  object
 2   Weiblich/Männlich                   12828 non-null  object
 3   Grübchenabstand DL-DR [mm]          12828 non-null  object
 4   Rumpflänge VP-DM [mm]               12828 non-null  object
 5   Rumpfneigung VP-DM [°]              12828 non-null  object
 6   Lotabweichung VP-DM [°]             12828 non-null  object
 7   Seitabweichung VP-DM (RMS) [mm]     12828 non-null  object
 8   Oberflächenrotation (RMS) [°]       12828 non-null  object
 9   Kyphosewinkel VP-T12 [°]            12826 non-null  object
 10  Lordosewinkel T12-DM [°]            12824 non-null  object
 11  Beckenneigung (Symmetrielinie) [°]  12828 non-null  object
 12  Beckentorsion DL-DR [°]             12828 non-null  object
 13  Beckenhochstand [°]                 12827 non-null  object
 14  Beckenrotation [°]                  12790 non-null  object
dtypes: datetime64[ns](1), object(14)
memory usage: 1.5+ MB

In [40]:
# accessing the dates after conversion 
k_pseudonymized['Erstellt am'].dt.date

0        2013-01-07
1        2013-01-07
2        2013-01-07
3        2015-02-10
4        2015-02-10
            ...
12823    2017-01-28
12824    2016-12-03
12825    2016-12-03
12826    2020-03-04
12827    2020-02-15
Name: Erstellt am, Length: 12828, dtype: object

In [41]:
# Accessing the time
k_pseudonymized['Erstellt am'].dt.time

0        11:58:35
1        11:57:35
2        11:49:17
3        04:28:13
4        04:27:03
           ...
12823    23:00:51
12824    11:28:06
12825    11:09:46
12826    02:29:53
12827    06:11:57
Name: Erstellt am, Length: 12828, dtype: object

In [42]:
# working with the date only
k_pseudonymized['Erstellt am'] = pd.to_datetime(k_pseudonymized['Erstellt am']).dt.date
k_pseudonymized['Erstellt am'] = pd.to_datetime(k_pseudonymized['Erstellt am'])
# checking the first 5 after conversion
k_pseudonymized.head()

,Erstellt am,age,Weiblich/Männlich,Grübchenabstand DL-DR [mm],Rumpflänge VP-DM [mm],Rumpfneigung VP-DM [°],Lotabweichung VP-DM [°],Seitabweichung VP-DM (RMS) [mm],Oberflächenrotation (RMS) [°],Kyphosewinkel VP-T12 [°],Lordosewinkel T12-DM [°],Beckenneigung (Symmetrielinie) [°],Beckentorsion DL-DR [°],Beckenhochstand [°],Beckenrotation [°]
0,2013-01-07,"(60, 70]",F,"106,6",520,"13,3","-4,8","16,3","6,909289","43,9","37,3","39,6","2,2","3,7","-0,4"
1,2013-01-07,"(60, 70]",F,"106,3","506,9","10,5","-4,7","14,5","8,003676","36,8","40,6","39,9","1,8","1,6","-2,2"
2,2013-01-07,"(60, 70]",F,106,"513,7",10,"-4,5","13,7","4,481077",37,"39,4","39,8",2,"1,7","0,2"
3,2015-02-10,"(40, 50]",F,"102,1","445,9","5,3","-0,7","4,2","3,060272","38,1","36,9","34,5","-0,9","3,3","4,6"
4,2015-02-10,"(40, 50]",F,"102,1","448,6","4,8","-0,7","4,9","3,081126","38,4",37,"32,1","-0,8","3,3","2,3"

In [43]:
k_pseudonymized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12828 entries, 0 to 12827
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Erstellt am                         12828 non-null  datetime64[ns]
 1   age                                 12828 non-null  object
 2   Weiblich/Männlich                   12828 non-null  object
 3   Grübchenabstand DL-DR [mm]          12828 non-null  object
 4   Rumpflänge VP-DM [mm]               12828 non-null  object
 5   Rumpfneigung VP-DM [°]              12828 non-null  object
 6   Lotabweichung VP-DM [°]             12828 non-null  object
 7   Seitabweichung VP-DM (RMS) [mm]     12828 non-null  object
 8   Oberflächenrotation (RMS) [°]       12828 non-null  object
 9   Kyphosewinkel VP-T12 [°]            12826 non-null  object
 10  Lordosewinkel T12-DM [°]            12824 non-null  object
 11  Beckenneigung (Symmetrielinie) [°]  12828 non-null  object
 12  Beckentorsion DL-DR [°]             12828 non-null  object
 13  Beckenhochstand [°]                 12827 non-null  object
 14  Beckenrotation [°]                  12790 non-null  object
dtypes: datetime64[ns](1), object(14)
memory usage: 1.5+ MB

....
<hr>
<i>1. filter from 2016 till date (lets get a count on data points)</i> <br>
<i>2. apply stratified sampling to divide the data into two sets (1 set to be used for Expert Labels and the other to use medical rules label) </i> <br>
<i>3. then from both sets, then we have to apply stratified sampling to get samples to be labelled (keeping in mind how much/ percentage sample is representative of the data)</i>
<hr>

In [44]:
# Earliest date of 2016: '2016-01-02'
# Till date: k_pseudonymized['Erstellt am'].max() : '2021-04-11'

In [45]:
# 1. filter from 2016 till date (lets get a count on data points)
k_pseudonymized = k_pseudonymized[(k_pseudonymized['Erstellt am'] >= '2016-01-01') & (k_pseudonymized['Erstellt am'] <= k_pseudonymized['Erstellt am'].max())]

In [46]:
# after filtering our date, we are left with 6960 samples
k_pseudonymized.shape

(6960, 15)

In [47]:
k_pseudonymized.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6960 entries, 6 to 12827
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Erstellt am                         6960 non-null   datetime64[ns]
 1   age                                 6960 non-null   object
 2   Weiblich/Männlich                   6960 non-null   object
 3   Grübchenabstand DL-DR [mm]          6960 non-null   object
 4   Rumpflänge VP-DM [mm]               6960 non-null   object
 5   Rumpfneigung VP-DM [°]              6960 non-null   object
 6   Lotabweichung VP-DM [°]             6960 non-null   object
 7   Seitabweichung VP-DM (RMS) [mm]     6960 non-null   object
 8   Oberflächenrotation (RMS) [°]       6960 non-null   object
 9   Kyphosewinkel VP-T12 [°]            6958 non-null   object
 10  Lordosewinkel T12-DM [°]            6959 non-null   object
 11  Beckenneigung (Symmetrielinie) [°]  6960 non-null   object
 12  Beckentorsion DL-DR [°]             6960 non-null   object
 13  Beckenhochstand [°]                 6960 non-null   object
 14  Beckenrotation [°]                  6952 non-null   object
dtypes: datetime64[ns](1), object(14)
memory usage: 870.0+ KB

In [48]:
# minimum date
k_pseudonymized['Erstellt am'].min()

Timestamp('2016-01-02 00:00:00')

In [49]:
# maximum date
k_pseudonymized['Erstellt am'].max()

Timestamp('2021-04-11 00:00:00')

In [50]:
# 2. apply stratified sampling to divide the data into two sets 
# (1 set to be used for Expert Labels and the other to use medical rules label)

# let check the value counts of (age) column in other to stratify it across the division (Expert and medical rules) 
k_pseudonymized['age'].value_counts()

(40, 50]     1271
(30, 40]     1266
(20, 30]     1123
(50, 60]     1115
(1, 15]       964
(60, 70]      528
(15, 20]      437
(70, 150]     256
Name: age, dtype: int64

In [51]:
# let save the dataset of 2016 till date as 2016_k_pseudonymized.csv
k_pseudonymized.to_csv('2016_k_pseudonymized.csv',index=False)

In [52]:
k_pseudonymized_2016 = pd.read_csv('2016_k_pseudonymized.csv')
k_pseudonymized_2016.head()

,Erstellt am,age,Weiblich/Männlich,Grübchenabstand DL-DR [mm],Rumpflänge VP-DM [mm],Rumpfneigung VP-DM [°],Lotabweichung VP-DM [°],Seitabweichung VP-DM (RMS) [mm],Oberflächenrotation (RMS) [°],Kyphosewinkel VP-T12 [°],Lordosewinkel T12-DM [°],Beckenneigung (Symmetrielinie) [°],Beckentorsion DL-DR [°],Beckenhochstand [°],Beckenrotation [°]
0,2016-05-05,"(20, 30]",F,69,440,"5,3","-1,3","2,4","3,270796","35,3","26,9","29,9","2,9",0,"-0,7"
1,2016-05-05,"(20, 30]",F,69,"446,7","6,2","-1,3","1,7","2,402576","36,4","25,3","27,7","2,5",0,"-0,2"
2,2016-05-05,"(20, 30]",F,69,"445,3","6,4","-0,5","1,5","3,249607","39,2","27,1","28,7","1,2","2,4","0,1"
3,2016-03-01,"(40, 50]",M,"88,6","462,7","2,8","1,6","6,6","7,114058","42,8","29,7","15,3","-7,9","7,8","12,2"
4,2016-03-01,"(40, 50]",M,"87,8","462,1","1,3","0,1","8,2","5,915843","38,7","29,2","13,8",-5,"7,8","-1,6"

In [53]:
k_pseudonymized_2016['Erstellt am'] = pd.to_datetime(k_pseudonymized_2016['Erstellt am'])
k_pseudonymized_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6960 entries, 0 to 6959
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Erstellt am                         6960 non-null   datetime64[ns]
 1   age                                 6960 non-null   object
 2   Weiblich/Männlich                   6960 non-null   object
 3   Grübchenabstand DL-DR [mm]          6960 non-null   object
 4   Rumpflänge VP-DM [mm]               6960 non-null   object
 5   Rumpfneigung VP-DM [°]              6960 non-null   object
 6   Lotabweichung VP-DM [°]             6960 non-null   object
 7   Seitabweichung VP-DM (RMS) [mm]     6960 non-null   object
 8   Oberflächenrotation (RMS) [°]       6960 non-null   object
 9   Kyphosewinkel VP-T12 [°]            6958 non-null   object
 10  Lordosewinkel T12-DM [°]            6959 non-null   object
 11  Beckenneigung (Symmetrielinie) [°]  6960 non-null   object
 12  Beckentorsion DL-DR [°]             6960 non-null   object
 13  Beckenhochstand [°]                 6960 non-null   object
 14  Beckenrotation [°]                  6952 non-null   object
dtypes: datetime64[ns](1), object(14)
memory usage: 815.8+ KB

In [54]:
# 2. apply stratified sampling to divide the data into two sets 
# (1 set to be used for Expert Labels and the other to use medical rules label)

# let check the value counts of (age) column in other to stratify it across the division (Expert and medical rules) 
k_pseudonymized_2016['age'].value_counts()

(40, 50]     1271
(30, 40]     1266
(20, 30]     1123
(50, 60]     1115
(1, 15]       964
(60, 70]      528
(15, 20]      437
(70, 150]     256
Name: age, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split
expert_labels,medical_rules = train_test_split(k_pseudonymized_2016,test_size=0.5,stratify=k_pseudonymized_2016['age'])

In [56]:
# percentage for the expert labelling
expert_labels['age'].value_counts()

(40, 50]     636
(30, 40]     633
(20, 30]     561
(50, 60]     558
(1, 15]      482
(60, 70]     264
(15, 20]     218
(70, 150]    128
Name: age, dtype: int64

In [57]:
# percentage for the madical rules
medical_rules['age'].value_counts()

(40, 50]     635
(30, 40]     633
(20, 30]     562
(50, 60]     557
(1, 15]      482
(60, 70]     264
(15, 20]     219
(70, 150]    128
Name: age, dtype: int64

In [58]:
# saving the divided data sets

In [59]:
# medical rules
medical_rules.to_csv('medical_rules.csv', index=False)

In [60]:
# Exepert labelling
expert_labels.to_csv('expert_labels.csv',index=False)

# Reading the divided stratified files

In [61]:
# reading the files
med = pd.read_csv('medical_rules.csv')
med.head()

,Erstellt am,age,Weiblich/Männlich,Grübchenabstand DL-DR [mm],Rumpflänge VP-DM [mm],Rumpfneigung VP-DM [°],Lotabweichung VP-DM [°],Seitabweichung VP-DM (RMS) [mm],Oberflächenrotation (RMS) [°],Kyphosewinkel VP-T12 [°],Lordosewinkel T12-DM [°],Beckenneigung (Symmetrielinie) [°],Beckentorsion DL-DR [°],Beckenhochstand [°],Beckenrotation [°]
0,2017-01-08,"(60, 70]",F,"73,3","496,5","3,3","0,1","12,6","4,431038","48,2","46,9","22,4","4,1",-2,5
1,2017-11-27,"(30, 40]",F,"112,5",524,1,"0,3","9,7","4,358054","38,1","30,2","18,4","0,2",-3,"-1,5"
2,2018-04-12,"(40, 50]",M,"109,2","513,9","4,7","1,1","9,7","2,94075","42,3",28,"22,5","2,3","0,5","-4,8"
3,2018-09-21,"(40, 50]",F,"97,1",445,"4,9","-0,4","2,7","1,899156","37,2","28,9",36,"0,2","-1,9","1,9"
4,2018-02-08,"(15, 20]",F,"68,1",465,"2,8","-1,8","4,4","5,628873","17,1","18,7","18,1","-0,3","-1,9","-5,1"

In [62]:
expert = pd.read_csv('expert_labels.csv')
expert.head()

,Erstellt am,age,Weiblich/Männlich,Grübchenabstand DL-DR [mm],Rumpflänge VP-DM [mm],Rumpfneigung VP-DM [°],Lotabweichung VP-DM [°],Seitabweichung VP-DM (RMS) [mm],Oberflächenrotation (RMS) [°],Kyphosewinkel VP-T12 [°],Lordosewinkel T12-DM [°],Beckenneigung (Symmetrielinie) [°],Beckentorsion DL-DR [°],Beckenhochstand [°],Beckenrotation [°]
0,2018-01-30,"(40, 50]",F,99,"489,9","4,7","0,3","4,4","3,970195","53,2","29,4","17,2",1,"-2,7","-0,2"
1,2016-08-31,"(60, 70]",F,"97,2","445,4","4,1","4,3","4,6","2,995909","40,6",28,"22,2","2,2","2,3","-8,7"
2,2018-08-20,"(60, 70]",M,"109,2","520,2",6,"0,9","6,9","3,387373","38,6","20,3","5,1","-3,2","-0,9","1,6"
3,2017-10-18,"(15, 20]",F,"99,8","486,7","2,3","1,9","12,4","6,529443","20,7","29,1","26,3",-1,-9,"5,5"
4,2019-11-04,"(30, 40]",M,"88,9","433,2","9,2","0,4","2,1","2,934328","61,5","49,9","40,4","2,9","2,1","1,7"